sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kffw/u1YwL9qXiGdIUSM9Nc/qo2vnmuVR+iurMT8jSHGpvhklalx0OGb07KmaYF8odHnlq9D1ffxk+HwUgc4qwLEUqskz/2aAIM2ygYve+McBJ4gf9WNmuC/0xx4ZGRF23rmElKVSheksQgtUwvUKB682ICairzUD1hSknUwO01yhsTNzWkXt75747ZlmmVqrdaQ6GWrkuDyH9QLBaJaBbvLfYRa+06J79ogu/ZlPr8OeQz+IfOvnQFrhUF1iOo0Uav35o4IIKuBX3LnZ767UjVPf23OCft001FqP+a25tYRBwv2Q6aUeGTzmEn2rntjXgx41bNlD27hgamr0+p+2M+BJHxtd0YauJopIx+v1LDZXR+fHFOCCK9ef9JxV6eNtD6hb+mOa5KoGb0DZC48nLGzLezk54OT+JTc8SgNvHEMVQj1pWXmI7yuO4XWr8duJdBHZE3ZYaY/gFXUW075jwelRI+nWoP63+22MNZxqSvC37MABI6efCkIhJz1y0HmTBbYGltQfnEmAR5b3fkT4qfta0B7/cL677OyLg1d3uyTPbYghUCIClcALNgkV1jWlRSUa9/gRgbeL8Dh4xKIxhqXafkKsX8U9ypg+FbLUMzY1e+tksBxtrIN5u/SZxD+bX3ud/0i4vDCxVdezWB4hLcgGdWk5pUoIQlmPQwuJzI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Woman-Who-Did_4396
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy